const TechnicalDetails = () => {
  return (
    <section className="grid w-full gap-3 p-3">
      <h2 className="text-3xl font-bold">Technical Details</h2>
      <h3 className="text-lg font-semibold">How it works</h3>
      <p>
        This mod functions exclusively during simulation time. It retrieves the
        previous state and configuration from a JSON file generated by the mod
        while the zone is running, eliminating the necessity to alter your
        savefile. When you exit a zone, any modifications made by the mod are
        automatically undone, restoring the original state. Furthermore, the
        mod’s service is automatically halted when you switch to a different
        household.
      </p>
      <p>
        You can safely retain this mod in your mod folder, even if you don’t
        actively use it. It won’t introduce any delays to the pie menu or affect
        other aspects of the game. In fact, as long as you refrain from adding
        any sims to the Skewer, the game will function as if no mod were
        installed.
      </p>
      <h3 className="text-lg font-semibold">Selectable Sims</h3>
      {/* <p>
        When you start a game in The Sims 4, you must select a Household to
        begin playing. Internally, the game adds the sims from that household to
        a list called &quot;Selectable Sims&quot; to determine which sims can be
        selected using the portraits at the bottom of the screen (this bar is
        called Skewer).
        <br />
        <br />
        Sim Control Hub allows you to expand this list by adding sims from other
        Households. This involves modifying several parts of the game, which is
        why most of the functionalities were implemented using Python Scripts.
        To achieve this, the mod introduces a new service that only runs during
        simulation time and restore everything back to normal before leaving the
        zone ensuring there is no risk of corrupting a saved game.
        <br />
        Most injections that modify the game code do not touch anything outside
        of this mod, so as long as no external sim is added to the active
        household, the game will function as if no mods were installed.
      </p> */}
      <p>
        When you embark on a game in The Sims 4, your first crucial decision is
        selecting a Household to dive into. Behind the scenes, the game
        populates a list known as ‘Selectable Sims’, which determines which sims
        can be chosen via the portraits displayed at the bottom of the screen
        (referred to as the Skewer).
      </p>
      <p>
        Sim Control Hub provides the capability to augment this list by
        incorporating sims from other households. Achieving this involves making
        modifications to various aspects of the game, which is why the majority
        of functionalities within this mod are implemented using Python Scripts.
      </p>
      <h3 className="text-lg font-semibold">Situations</h3>
      <p>
        When you add a new selectable Sim who is currently present in the active
        zone, they are likely engaged in some specific situation. For instance,
        it could be a casual ‘WalkBy’ scenario, a hired mixologist tending the
        bar, someone leisurely fishing by the pond, and so forth. These
        situations can vary from one zone to another, which complicates the task
        of controlling a Sim because they directly impact their autonomy.
      </p>
      <p>
        Now, the straightforward approach would be to restrict control only to
        Sims in ‘WalkBy’ situations. However, I decided to take a calculated
        risk and allow control over any Sim. Yes, that means you can steer the
        destiny of a store vendor, Father Winter himself, or any other Sim in
        your virtual world. Initially, managing these Sims doesn’t pose
        significant issues. As long as you position them near the relevant areas
        where they naturally perform their tasks, they will continue to do so
        automatically.
      </p>
      <p>
        But here’s the caveat: It’s essential to keep this in mind. There’s a
        multitude of situations to consider, and I’d greatly appreciate any
        reports of issues arising from controlling Sims in specific
        circumstances. After all, unexpected glitches can occur.
      </p>
      <h3 className="text-lg font-semibold">Leaving Situations</h3>
      <p>
        In the game, all situations progress through distinct states. However,
        when most situations reach their conclusion, they transition into a
        ‘Leave State,’ during which each participating sim assumes a ‘Leaving’
        role. Unfortunately, this role can lead to an issue: Selectable Sims
        added to the Skewer by this mod may become trapped in an endless loop,
        attempting to leave the area but remaining unable to do so. You can
        easily notice this when you see a Sim standing still, endlessly
        restarting an idle animation.
      </p>
      <p>
        Interestingly, even in the unmodified game, there are situations with
        this bugged animation. For instance, during the ‘Welcome Wagon’ event,
        neighborhood Sims waiting for an invitation to enter may become trapped
        in this odd animation. This occurs because they repeatedly use the
        interaction ‘Go to front door’ until they are finally invited into the
        residence.
      </p>
      <p>
        Fortunately, I’ve devised a solution: my mod actively monitors changes
        in the situation’s state for any selectable Sim added by this mod and
        promptly removes those situations that acquire a ‘Leaving Role‘.
      </p>
      <p>
        Now, if you happen to stumble upon any of these stuck Sims, here’s the
        secret recipe: send them back home, and then bring them right back to
        the current zone. Voilà! This little maneuver should untangle any
        potential issues, freeing them from their situation-induced limbo. Also,
        don’t forget to take note and report the steps that led to this bug.
      </p>
      <h3 className="text-lg font-semibold">Homeless Sims</h3>
      <p>
        Adding homeless selectable sims to the skewer presented a significant
        challenge, but it’s now achievable.
      </p>
      <p>
        In the unmodified game, when you play with a household and find yourself
        in a different area than the residential lot, any selectable Sim at home
        automatically heads to work. However, playable Sims in the active area
        who need to attend their careers must first return home. The issue
        arises with homeless Sims; they lack a home altogether, causing
        complications. To address this, my mod introduces a small patch that
        allows homeless Sims to enter a null zone and engage in any Rabbit Hole
        activity that typically requires a home lot. I’ve thoroughly tested this
        feature, and there shouldn’t be any related problems.
      </p>
      <h3 className="text-lg font-semibold">Travel Groups</h3>
      <p>
        I’ve added a small module with interactions specifically for handling
        Travel Groups. I did this because Travel Groups can cause quite a few
        issues, especially since the base game wasn’t originally designed to
        control Sims from different households and travel groups.
      </p>
      <p>Here’s a breakdown of how it works:</p>
      <ol className="list-decimal ml-5">
        <li>
          <h3 className="font-semibold">Travel Group Types:</h3>
          <p>
            There are two main types of Travel Groups: Vacation Groups and Stay
            Over Groups.
          </p>
          <ul className="list-disc ml-5">
            <li>
              <b>Vacation Groups:</b> These are formed when a Sim uses the “Take
              a Vacation” interaction. Essentially, it creates a Travel Group
              consisting of all Sims currently on vacation in another region.
              The Sim who initiated the vacation becomes the group leader.
            </li>
            <li>
              <b>Stay Over Groups:</b> Introduced with the “Growing Together”
              DLC, these groups are created when Sims are invited to stay
              overnight in another household’s residence. Notably, the Sims from
              the active household (the one you’re controlling) do not become
              part of this Travel Group.
            </li>
          </ul>
        </li>
        <li>
          <h3 className="font-semibold">Constraints:</h3>
          <ul className="list-disc ml-5">
            <li>
              In the base game, each household can have only one Travel Group.
              If a Sim from the active household is on vacation, there cannot be
              any Stay Over guests. Conversely, if there are Stay Over guests,
              no Sims from the active household can be vacationing in another
              region.
            </li>
            <li>
              When a Sim is vacationing in another region, you’ll notice that
              you cannot select Sims who are not part of their Travel
              Group—unless you invite them using the “Join Vacation”
              interaction.
            </li>
          </ul>
        </li>
      </ol>
      <p>
        When you consider it carefully, this introduces significant complexity
        to the mod. It must evaluate a multitude of cases. Here are some
        examples:
      </p>
      <ul className="list-disc ml-5">
        <li>
          Controlling a Sim who is a stay over guest in the active household
          (where the active household itself is not part of the Travel Group).
        </li>
        <li>
          Controlling two Sims from different households, both of whom are stay
          over guests in other households.
        </li>
        <li>
          Handling Sims from different Travel Groups who happen to be
          vacationing in the same region.
        </li>
      </ul>
      <p>
        Fortunately, I’ve thoroughly considered all possible scenarios, so there
        shouldn’t be any issues. Moreover, identifying glitches related to
        Travel Groups is straightforward: If a Sim that should be controllable
        cannot be selected, they’ll appear grayed out, and you won’t be able to
        view their needs, relationships, and other relevant information.&nbsp;
        <i className="text-orange-200">
          If you encounter this situation, please submit a report with the steps
          to reproduce it.
        </i>
      </p>
      <h3 className="text-lg font-semibold">Error Logging</h3>
      <p>
        This mod includes a logger specifically designed to record any errors
        that might occur within its functionality. If, for any reason, you
        suspect that something isn’t working correctly, you can check the folder
        where you’ve stored the mod. Look for a .log file—it should contain
        information about any errors encountered. If you find such a file, feel
        free to share its contents with me, and I’ll investigate to determine
        what might be going wrong.
      </p>
    </section>
  );
};
export default TechnicalDetails;
